=== integratedPRIVATE/directDebitWHMCS/prototyping/samples/request.dtd
<!-- Stores the entire message, must be root -->
<!ELEMENT SecurePayMessage (MessageInfo, MerchantInfo, RequestType, Periodic?, Token?)>

<!ELEMENT MessageInfo (messageID, messageTimestamp, timeoutValue, apiVersion)>
<!ELEMENT messageID (#PCDATA)>
<!ELEMENT messageTimestamp (#PCDATA)>
<!ELEMENT timeoutValue (#PCDATA)>
<!ELEMENT apiVersion (#PCDATA)>

<!ELEMENT MerchantInfo (merchantID, password)>
<!ELEMENT merchantID (#PCDATA)>
<!ELEMENT password (#PCDATA)>

<!ELEMENT RequestType (#PCDATA)>

<!ELEMENT Periodic (PeriodicList)>
<!ELEMENT PeriodicList (PeriodicItem*)>
<!ATTLIST PeriodicList count CDATA #REQUIRED>


<!-- define elements for PeriodicList -->
<!ELEMENT PeriodicItem (actionType, clientID, CreditCardInfo?, DirectEntryInfo?, amount?, periodicType?, paymentInterval?, startDate?, numberOfPayments?)>
<!ATTLIST PeriodicItem ID CDATA #REQUIRED>

<!-- define elements for PeriodicItem -->
<!ELEMENT actionType (#PCDATA)>
<!ELEMENT clientID (#PCDATA)>
<!ELEMENT CreditCardInfo (cardNumber, cvv?, expiryDate, recurringFlag?, transactionReference?)>
<!ELEMENT DirectEntryInfo (bsbNumber, accountNumber, accountName, creditFlag?)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT currency (#PCDATA)>
<!ELEMENT periodicType (#PCDATA)>
<!ELEMENT paymentInterval (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT numberOfPayments (#PCDATA)>

<!-- define elements for CreditCardInfo -->
<!ELEMENT cardNumber (#PCDATA)>
<!ELEMENT cvv (#PCDATA)>
<!ELEMENT expiryDate (#PCDATA)>
<!ELEMENT recurringFlag (#PCDATA)>
<!ELEMENT transactionReference (#PCDATA)>

<!-- define elements for DirectEntryInfo -->
<!ELEMENT bsbNumber (#PCDATA)>
<!ELEMENT accountNumber (#PCDATA)>
<!ELEMENT accountName (#PCDATA)>
<!ELEMENT creditFlag (#PCDATA)>

<!-- define elements for Token-->
<!ELEMENT Token (TokenList)>
<!ATTLIST TokenItem ID NMTOKEN #REQUIRED>
<!ELEMENT TokenList (TokenItem)>
<!ATTLIST TokenList count NMTOKEN #REQUIRED>
<!ELEMENT TokenItem (cardNumber?, expiryDate?, tokenType?, amount?, transactionReference?, tokenValue?)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT cardNumber (#PCDATA)>
<!ELEMENT expiryDate (#PCDATA)>
<!ELEMENT tokenType (#PCDATA)>
<!ELEMENT tokenValue (#PCDATA)>
<!ELEMENT transactionReference (#PCDATA)>

=== integratedPRIVATE/directDebitWHMCS/_archive/prototyping/samples/triggeringpayment.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE SecurePayMessage SYSTEM "request.dtd">

<!-- TRIGGERING A PAYMENT -->
<SecurePayMessage>

    <MessageInfo>
        <messageID>8af793f9af34bea0ecd7eff71c94d6</messageID>
        <messageTimestamp>20040710050758444000+600</messageTimestamp>
        <timeoutValue>60</timeoutValue>
        <apiVersion>spxml-3.0</apiVersion>
    </MessageInfo>

    <MerchantInfo>
        <merchantID>ABC0001</merchantID>
        <password>abc123</password>
    </MerchantInfo>

    <RequestType>Periodic</RequestType>
    <Periodic>
        <PeriodicList count="1">
            <PeriodicItem ID="1">
                <actionType>trigger</actionType>
                <transactionReference>Payment Reference</transactionReference>
                <clientID>test3</clientID>
                <amount>1400</amount>
            </PeriodicItem>
        </PeriodicList>
    </Periodic>
    
</SecurePayMessage>

=== integratedPRIVATE/directDebitWHMCS/prototyping/samples/storingcardtoken.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE SecurePayMessage SYSTEM "request.dtd">

<!-- STORING A CARD AS A TOKEN -->
<SecurePayMessage>

    <MessageInfo>
        <messageID>8af793f9af34bea0ecd7eff711c9d3</messageID>
        <messageTimestamp>20110710015921142000+600</messageTimestamp>
        <timeoutValue>60</timeoutValue>
        <apiVersion>spxml-3.0</apiVersion>
    </MessageInfo>

    <MerchantInfo>
        <merchantID>ABC00</merchantID>
        <password>abc123</password>
    </MerchantInfo>

    <RequestType>addToken</RequestType>
    <Token>
        <TokenList count="1">
            <TokenItem ID="1">
                <cardNumber>4444333322221111</cardNumber>
                <expiryDate>11/25</expiryDate>
                <tokenType>1</tokenType>
                <amount>1100</amount>
                <transactionReference>MyCustomer</transactionReference>
            </TokenItem>
        </TokenList>
    </Token>

</SecurePayMessage>

=== integratedPRIVATE/directDebitWHMCS/prototyping/samples/lookuptoken.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE SecurePayMessage SYSTEM "request.dtd">

<!-- LOOK UP A TOKEN -->
<SecurePayMessage>

    <MessageInfo>
        <messageID>8af793f9af34bea0ecd7eff71a55f6</messageID>
        <messageTimestamp>20110710042843759000+600</messageTimestamp>
        <timeoutValue>60</timeoutValue>
        <apiVersion>spxml-3.0</apiVersion>
    </MessageInfo>

    <MerchantInfo>
        <merchantID>ABC00</merchantID>
        <password>abc123</password>
    </MerchantInfo>

    <RequestType>lookupToken</RequestType>
    <Token>
        <TokenList count="1">
            <TokenItem ID="1">
                <tokenValue>1234123412341234</tokenValue>
            </TokenItem>
        </TokenList>
    </Token>
    
</SecurePayMessage>

=== integratedPRIVATE/directDebitWHMCS/_archive/prototyping/samples/storingcardpayor.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE SecurePayMessage SYSTEM "request.dtd">

<!-- STORING A CARD AS A PAYOR -->
<SecurePayMessage>

    <MessageInfo>
        <messageID>8af793f9af34bea0ecd7eff71b37ef</messageID>
        <messageTimestamp>20040710044409342000+600</messageTimestamp>
        <timeoutValue>60</timeoutValue>
        <apiVersion>spxml-3.0</apiVersion>
    </MessageInfo>

    <MerchantInfo>
        <merchantID>ABC0001</merchantID>
        <password>abc123</password>
    </MerchantInfo>

    <RequestType>Periodic</RequestType>
    <Periodic>
        <PeriodicList count="1">
            <PeriodicItem ID="1">
                <actionType>add</actionType>
                <clientID>test3</clientID>
                <CreditCardInfo>
                    <cardNumber>4444333322221111</cardNumber>
                    <cvv>123</cvv>
                    <expiryDate>09/25</expiryDate>
                </CreditCardInfo>
                <amount>1100</amount>
                <periodicType>4</periodicType>
            </PeriodicItem>
        </PeriodicList>
    </Periodic>

</SecurePayMessage>
